---
name: Validate Pull Requests ğŸ·ï¸âœ…
run-name: Validate Pull Requests ğŸ·ï¸âœ…

on:
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-pull-requests:
    name: Validate Pull Request Title ğŸ·ï¸âœ…
    uses: Bleala/Reusable-Workflows/.github/workflows/reusable-pull-requests-linter.yaml@main
    permissions:
      # required to read pull requests
      pull-requests: read
    secrets:
      GITHUB_WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
