---
name: Lint YAML Files ğŸ“ğŸ•µï¸ğŸ”
run-name: Lint YAML Files ğŸ“ğŸ•µï¸ğŸ”

on:
  push:
    branches:
      - '**'
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/.yamllint'
  workflow_dispatch:
    inputs:
      source:
        description: 'Specify the branch/tag to checkout (default: main)'
        required: false
        default: 'main'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml-files:
    name: Lint YAML Files ğŸ“ğŸ•µï¸ğŸ”
    uses: Bleala/Reusable-Workflows/.github/workflows/reusable-yaml-linter.yaml@main
    with:
      ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.source || github.ref }}
    permissions:
      # for actions/checkout to fetch code
      contents: read
    secrets:
      GITHUB_WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
